main/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_network.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/social_network/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from .views import *
from . import views

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('all_users/', AllUsers.as_view(), name='all_users'),
    path('registration/', Registration.as_view(), name='registration'),
    path('login/', LoginViewMy.as_view(), name='login'),
    path('profile/<int:pk>', page_with_message, name='profile'),
    path('logout/', views.logout_profile, name='logout'),
    path('update/<int:pk>', update_page, name='update'),
    path('edit_c/<int:pk>', EditComment.as_view(), name='edit_c'),
    path('del_c/<int:pk>', DelComment.as_view(), name='del_c'),
    path('del_user/<int:pk>', wanna_delete, name='wanna_delete'),
    path('delete_user/<int:pk>', delete_u_and_p, name='delete1'),

]

main/social_network/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    image = models.ImageField(upload_to='user_image', blank=True, null=True)
    page = models.OneToOneField('Profile', on_delete=models.CASCADE, null=True)
    commentaries = models.ForeignKey('Message', on_delete=models.CASCADE, null=True, blank=True)


class Profile(models.Model):
    date_birth = models.DateField(blank=True, default=None, null=True)
    status = models.CharField(max_length=1000, blank=True, default='123')
    about = models.TextField(blank=True, default='...')


class Message(models.Model):
    username = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True, default=None, db_column='person')
    page = models.ForeignKey('Profile', on_delete=models.CASCADE, null=True, blank=True, default=None)
    text = models.TextField(max_length=1000, blank=True, default='')
    image = models.ImageField(upload_to='comments_image', blank=True, null=True)
    date = models.DateTimeField(auto_now=True)
    destination = models.CharField(max_length=299, null=True, blank=True, default=None)

main/social_network/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from social_network.models import Message


class RegistrationForm(UserCreationForm):
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Придумайте пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'image']

        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'image': 'Аватарка',
            'email': 'Ваша почта'
        }


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text', 'image']
        widgets = {
            'text': forms.Textarea(attrs={'cols': 100, 'rows': 5, 'placeholder': 'Сообщение'}),
            'image': forms.ClearableFileInput()
        }
        labels = {
            'text': 'Оставить сообщение',
            'image': 'Изображение',
        }

    def clean_text(self):
        cd = self.cleaned_data
        if cd['text'] == '' or cd['text'] == ' ':
            raise forms.ValidationError('Комментарий не должен быть пустым.')
        return cd['text']

class UpdateForm(forms.Form):
    first_name = forms.CharField(label='Имя ')
    last_name = forms.CharField(label='Фамилия ')
    date_birth = forms.DateField(label='Дата вашего рождения ', widget=forms.DateInput(attrs={'type': 'date'}))
    status = forms.CharField(label='Статус ')
    about = forms.CharField(label='О себе ', widget=forms.Textarea(attrs={
                            'cols': 65, 'rows': 10, 'placeholder': 'Введите текст'}))
    image = forms.ImageField(label='Аватарка ', required=False)

main/social_network/views.py
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from social_network.forms import RegistrationForm, CommentsForm, UpdateForm
from social_network.models import Profile, User, Message


def index(request):
    p = Paginator(Message.objects.order_by('-date'), 50)
    if request.GET:
        page_object = p.get_page(request.GET.get('page_number'))
        number_of_page = request.GET.get('page_number')
    else:
        page_object = p.get_page(1)
        number_of_page = 1

    context = {
        'title': 'Главная страница',
        'page_object': page_object,
        'number_of_page': number_of_page
    }

    return render(request, 'social_network/index.html',
                  context=context )

class AllUsers(ListView):
    def get_queryset(self):
        return get_user_model().objects.filter(is_superuser=False)
    template_name = 'social_network/all_users.html'
    context_object_name = 'users_list'

class Registration(CreateView):
    form_class = RegistrationForm
    template_name = 'social_network/registration.html'
    extra_context = {
        'title': 'Создание пользователя'
    }
    success_url = reverse_lazy('main:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        user = self.object
        profile = Profile.objects.create()
        user.page = profile
        user.save()
        return response

class LoginViewMy(LoginView):
    form_class = AuthenticationForm
    template_name = 'social_network/login.html'
    extra_context = {'title': 'Авторизация'}
    success_url = reverse_lazy('main:index')

@login_required
def page_with_message(request, pk):
    user_object = get_user_model().objects.get(pk=pk)
    page_object = user_object.page

    if request.method == 'POST':
        form = CommentsForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.username = request.user
            f.page = page_object
            f.destination = user_object.username
            f.save()
    else:
        form = CommentsForm()

    message_q = page_object.message_set.all()
    context = {
        'user_object': user_object,
        'page_object': page_object,
        'message_q': message_q,
        'form': form,
        'title': user_object.username
    }
    return render(request, 'social_network/page.html', context=context)


@login_required
def update_page(request, pk):
    if pk == request.user.pk:
        if request.method == 'POST':
            form = UpdateForm(request.POST, request.FILES)
            if form.is_valid():
                cd = form.cleaned_data
                user = get_user_model().objects.get(pk=pk)
                user.first_name = cd['first_name']
                user.last_name = cd['last_name']
                if cd['image']:
                    user.image = cd['image']

                user.save()

                profile = Profile.objects.get(pk=pk)
                profile.status = cd['status']
                profile.date_birth = cd['date_birth']
                profile.about = cd['about']

                profile.save()

                return redirect(reverse_lazy('main:profile', kwargs={'pk': pk}))
        else:
            stub = get_user_model().objects.get(pk=pk).first_name
            stub2 = get_user_model().objects.get(pk=pk).last_name
            stub3 = get_user_model().objects.get(pk=pk).image
            stub4 = Profile.objects.get(pk=pk).status
            stub5 = Profile.objects.get(pk=pk).date_birth
            stub6 = Profile.objects.get(pk=pk).about

            dict1 = {
                'first_name': stub,
                'last_name': stub2,
                'image': stub3,
                'status': stub4,
                'date_birth': stub5,
                'about': stub6
            }

            form = UpdateForm(initial=dict1)
        context = {
            'form': form,
            'title': 'Редактирование данных'
        }
        return render(request, 'social_network/update.html', context=context)
    else:
        return redirect('/')

def wanna_delete(request, pk):
    return render(request, 'social_network/confirm_del_user.html', context={
                                                                                'title': 'Удаление пользователя',
                                                                                'pk': pk
                                                                                })

def delete_u_and_p(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    page = user.page
    page.delete()
    user.delete()
    return redirect('/')



class EditComment(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = CommentsForm
    template_name = 'social_network/edit_c.html'

    def dispatch(self, request, *args, **kwargs):
        self.return_key = request.GET.get('return_key')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if self.return_key:
            form.save()
            return redirect(reverse_lazy('main:profile', kwargs={'pk': self.return_key}))
        else:
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['return_key'] = self.return_key
        return context


class DelComment(LoginRequiredMixin, DeleteView):
    model = Message
    template_name = 'social_network/del_confirm.html'
    extra_context = {
        'title': 'Подтвердите удаление комментария'
    }

    def get_success_url(self):
        return reverse_lazy('main:profile', kwargs={'pk': self.return_key})

    def dispatch(self, request, *args, **kwargs):
        self.return_key = request.GET.get('return_key')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['return_key'] = self.return_key
        return context

def logout_profile(request):
    logout(request)
    return render(request, 'social_network/logout.html')

main/social_network/templates/social_network/all_users.html
{% extends 'social_network/base.html' %}

{% block navigation %}
    {% if user.is_authenticated %}
        <h3>{{ user.username }}</h3>
        <a href="{% url 'main:index' %}"><p>Главная</p></a>
        <a href="{% url 'main:all_users' %}"><p>Все пользователи</p></a>
        <a href="{% url 'main:profile' request.user.id %}"><p>Моя страничка</p></a>
        <a href="{% url 'main:logout' %}"><p>Выйти</p></a>
        <a href="{% url 'main:wanna_delete' request.user.id %}"><p>Удалить пользователя</p></a>
    {% else %}
        <a href="{% url 'main:index' %}"><p>Главная</p></a>
        <a href="{% url 'main:registration' %}"><p>Регистрация</p></a>
        <a href="{% url 'main:login' %}"><p>Войти</p></a>
    {% endif %}
{% endblock %}

{% block content %}
    <h2>Список пользователей кому можно написать</h2>
    {% for i in users_list %}
        <a href="{% url 'main:profile' i.pk %}"><p>{{ i.username }} -- {{ i.first_name }} {{ i.last_name }}</p></a>
        <hr>
    {% endfor %}
{% endblock %}

main/social_network/templates/social_network/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link type="text/css" href="{% static 'social_network/style.css' %}" rel="stylesheet">
</head>
<body>
    <div class="main_box">
        <div class ="navigation">{% block navigation %} {% endblock %}</div>

        {% block content %} {% endblock %}
    </div>
</body>
</html>

main/social_network/templates/social_network/confirm_del_user.html
{% extends 'social_network/base.html' %}
{% block navigation %}
     <a href="{% url 'main:index' %}"><p>Главная</p></a>
     <a href="{% url 'main:profile' pk %}"><p>Назад</p></a>
{% endblock %}
{% block content %}
    <h1 class="red_a">{{ title }}</h1>
    <a href="{% url 'main:delete1' pk %}"><button>УДАЛИТЬ ПОЛЬЗОВАТЕЛЯ</button></a>
{% endblock %}

main/social_network/templates/social_network/del_confirm.html
{% extends 'social_network/base.html' %}
{% block navigation %}
     <a href="{% url 'main:index' %}"><p>Главная</p></a>
     <a href="{% url 'main:profile' return_key %}"><p>Назад</p></a>
{% endblock %}
{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">УДАЛИТЬ</button>
    </form>
{% endblock %}

main/social_network/templates/social_network/edit_c.html
{% extends 'social_network/base.html' %}
{% block navigation %}
     <a href="{% url 'main:index' %}"><p>Главная</p></a>
     <a href="{% url 'main:profile' return_key %}"><p>Назад</p></a>
{% endblock %}
{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">СОХРАНИТЬ</button>
    </form>
{% endblock %}

main/social_network/templates/social_network/index.html
{% extends 'social_network/base.html' %}

{% block navigation %}
    {% if user.is_authenticated %}
        <h3>{{ user.username }}</h3>
        <a href="{% url 'main:index' %}"><p>Главная</p></a>
        <a href="{% url 'main:all_users' %}"><p>Все пользователи</p></a>
        <a href="{% url 'main:profile' request.user.id %}"><p>Моя страничка</p></a>
        <a href="{% url 'main:logout' %}"><p>Выйти</p></a>
        <a href="{% url 'main:wanna_delete' request.user.id %}"><p>Удалить пользователя</p></a>
    {% else %}
        <a href="{% url 'main:index' %}"><p>Главная</p></a>
        <a href="{% url 'main:all_users' %}"><p>Все пользователи</p></a>
        <a href="{% url 'main:registration' %}"><p>Регистрация</p></a>
        <a href="{% url 'main:login' %}"><p>Войти</p></a>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <h2>Последние 50 сообщений </h2>
    {% for i in page_object %}
        <p><b>{{ i.username }}</b> пишет: <b>{{ i.destination }}</b></p>
            <p>(<b>Дата комментария:</b> {{ i.date }})</p>
            <p>{{ i.text }}</p>
            {% if i.image %}
                <img src="{{ i.image.url }}" alt="Изображение коментария">
            {% endif %}
            <hr>
    {% endfor %}

    <ul class="pagination">
    {% if page_object.has_other_pages %}
        {% for j in page_object.paginator.page_range %}
            {% if j == number_of_page %}
                <li class="pag_ref"><div>{{ j }}</div></li>
            {% else %}
                <a href="{% url 'main:index' %}?page_number={{ j }}"><li class="pag_ref"><div>{{ j }}</div></li></a>
            {% endif %}
        {% endfor %}
    {% endif %}
    </ul>
{% endblock %}

main/social_network/templates/social_network/login.html
{% extends 'social_network/base.html' %}
{% block navigation %}
     <a href="{% url 'main:index' %}"><p>Назад</p></a>
{% endblock %}
{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">ОТПРАВИТЬ</button>
    </form>
{% endblock %}

main/social_network/templates/social_network/logout.html
{% extends 'social_network/base.html' %}

{% block navigation %}
        <a href="{% url 'main:index' %}"><p>Главная</p></a>
        <a href="{% url 'main:all_users' %}"><p>Все пользователи</p></a>
        <a href="{% url 'main:registration' %}"><p>Регистрация</p></a>
        <a href="{% url 'main:login' %}"><p>Войти</p></a>
{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <h2>Вы вышли из аккаунта</h2>
    {% for i in page_object %}
        <p><b>{{ i.username }}</b> пишет: <b>{{ i.destination }}</b></p>
            <p>(<b>Дата комментария:</b> {{ i.date }})</p>
            <p>{{ i.text }}</p>
            {% if i.image %}
                <img src="{{ i.image.url }}" alt="Изображение коментария">
            {% endif %}
            <hr>
    {% endfor %}

    <ul class="pagination">
    {% if page_object.has_other_pages %}
        {% for j in page_object.paginator.page_range %}
            {% if j == number_of_page %}
                <li class="pag_ref"><div>{{ j }}</div></li>
            {% else %}
                <a href="{% url 'main:index' %}?page_number={{ j }}"><li class="pag_ref"><div>{{ j }}</div></li></a>
            {% endif %}
        {% endfor %}
    {% endif %}
    </ul>
{% endblock %}

main/social_network/templates/social_network/page.html
{% extends 'social_network/base.html' %}
{% block navigation %}
    <h3>{{ user.username }}</h3>
     <a href="{% url 'main:index' %}"><p>Главная</p></a>
     <a href="{% url 'main:all_users' %}"><p>Все пользователи</p></a>
     <a href="{% url 'main:update'  request.user.pk %}"><p>Редактировать</p></a>
     <a href="{% url 'main:logout' %}"><p>Выйти</p></a>
     <a href="{% url 'main:wanna_delete' request.user.id %}"><p>Удалить пользователя</p></a>
{% endblock %}
{% block content %}
    <h2>Логин: {{ title }}</h2>
    <br>
    <h2>{{ user_object.first_name }} {{ user_object.last_name }}</h2>
    <p><b>Статус:</b> {{page_object.status}}</p>
    {% if user_object.image %}
        <img class="avatar" src="{{ user_object.image.url }}" alt="аватарка пользователя">
    {% endif %}
    <br>
    <p><b>Дата рождения:</b> {{page_object.date_birth}}</p>
    <p><b>Обо мне:</b> {{page_object.about}}</p>
    <br>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Оставить комментарий</button>
    </form>
    <br>
        {% for i in message_q %}
            <p><b>{{ i.username }}</b> пишет: (<b>Дата комментария:</b> {{ i.date }})</p>
            <p>{{ i.text }}</p>
            {% if i.image %}
                <img src="{{ i.image.url }}" alt="Изображение коментария">
            {% endif %}
            {% if i.username.username == request.user.username or i.destination == request.user.username %}
                <p>
                    <a href="{% url 'main:edit_c' i.pk %}?return_key={{ user_object.pk }}" ><span class="red_a">Редактировать</span></a>
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    <a href="{% url 'main:del_c' i.pk %}?return_key={{ user_object.pk }}" ><span class="red_a" >Удалить</span></a>
                </p>
            {% endif %}
            <hr>
        {% endfor %}



{% endblock %}

main/social_network/templates/social_network/registration.html
{% extends 'social_network/base.html' %}
{% block navigation %}
     <a href="{% url 'main:index' %}"><p>Назад</p></a>
{% endblock %}
{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">ОТПРАВИТЬ</button>
    </form>
{% endblock %}

main/social_network/templates/social_network/update.html
{% extends 'social_network/base.html' %}
{% block navigation %}
        <a href="{% url 'main:index' %}"><p>Главная</p></a>
        <a href="{% url 'main:all_users' %}"><p>Все пользователи</p></a>
        <a href="{% url 'main:profile' request.user.id %}"><p>Моя страничка</p></a>
        <a href="{% url 'main:logout' %}"><p>Выйти</p></a>
        <a href="{% url 'main:wanna_delete' request.user.id %}"><p>Удалить пользователя</p></a>
{% endblock %}
{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">СОХРАНИТЬ</button>
    </form>
{% endblock %}